# Generated by Django 2.2.5 on 2019-09-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cousemodel',
            name='coursename',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
